openapi: 3.0.0
info:
  title: Documentation-vue API
  description: Documentation-vue API
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server
tags:
  - name: auth
    description: Authorization
paths:
  /api/auth/register:
    post:
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                passwordConfirm:
                  type: string

      summary: Register a new user.
      responses:
        "200":
          description: A JSON object of token and user data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: "User registered."
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                      user:
                        type: object
                        properties:
                          name:
                            type: string
                          email:
                            type: string
        "422":
          description: A JSON object of validation error data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Validation errors"
                  data:
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                              example: "email"
                            message:
                              type: string
                              example: "validation.unique"

  /api/auth/login:
    post:
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

      summary: Login a user.
      responses:
        "200":
          description: A JSON object of token and user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: strin
                    example: "User logged."
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                      user:
                        type: object
                        properties:
                          name:
                            type: string
                          email:
                            type: string
        "400":
          description: A JSON object of token and user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                  data:
                    example: null
        "422":
          description: A JSON object of validation error data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Validation errors"
                  data:
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                              example: "password"
                            message:
                              type: string
                              example: "validation.min.string"
